version: '3'
services: 
  db1:
    image: mongo
  service1:
    build: 
      context: ./server/
      dockerfile: Dockerfile.1dev
    container_name: service1
    ports:
      - "5001:80"
    image: mickeysden/multi-docker-server-service1
    depends_on: 
      - db1
  service1-test:
    build: 
      context: ./server/
      dockerfile: Dockerfile.1test
    container_name: service1-test
    image: mickeysden/multi-docker-server-service1-test
    depends_on: 
      - service1
  service2:
    build: 
      context: ./server/
      dockerfile: Dockerfile.2dev
    container_name: service2
    ports:
      - "5002:80"
    image: mickeysden/multi-docker-server-service2
  service2-test:
    build: 
      context: ./server/
      dockerfile: Dockerfile.2test
    container_name: service2-test
    image: mickeysden/multi-docker-server-service2-test
    depends_on: 
      - service2
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: client
    image: mickeysden/multi-docker-client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports: 
      - '3000:3000'
    depends_on: 
      - client-test
      - service1-test
      - service2-test
    links: 
      - service1
  client-test:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: client-test
    volumes:
      - /app/node_modules
      - ./client:/app
    command: npm test